"""业务资产生成器（Module 6）：把汇总情报渲染成可下载的 Word/PPT/文本交付物。"""
import io
from datetime import date

from app.services.report_html import _fmt  # 复用数字格式化


# ---------------- 投资备忘录 (DOCX) ----------------
def build_investor_memo(intel: dict) -> bytes:
    import docx
    from docx.shared import Pt, RGBColor

    c = intel["company"]
    cur = (intel.get("financial") or {}).get("currency", "USD")
    d = docx.Document()
    d.add_heading(f"{c['name']} — Investor Memo", level=0)
    sub = d.add_paragraph(f"{c.get('industry') or ''} · {c.get('sector') or ''} · {c.get('location') or ''} · {date.today().isoformat()}")
    sub.runs[0].italic = True

    b = intel.get("briefing")
    if b:
        d.add_heading("Executive Summary", level=1)
        if b.get("summary"): d.add_paragraph(b["summary"])
        if b.get("what_happened"): d.add_paragraph(b["what_happened"])
        if b.get("why_it_matters"): d.add_paragraph(b["why_it_matters"])

    f = intel.get("financial")
    if f:
        d.add_heading("Financials", level=1)
        s = f["trend"]["summary"]; sc = f["scores"]
        d.add_paragraph(f"Latest revenue {_fmt(s.get('latest_revenue'), cur)} · YoY "
                        f"{s.get('yoy_revenue_growth')}% · Net margin {s.get('latest_net_margin')}% · "
                        f"Health {sc.get('financial_health')}/100, Risk {sc.get('risk')}/100")
        periods = f["trend"]["periods"]
        if periods:
            t = d.add_table(rows=1, cols=4); t.style = "Light Grid Accent 1"
            for i, h in enumerate(["Period", "Revenue", "Net Profit", "Net %"]):
                t.rows[0].cells[i].text = h
            for p in periods:
                row = t.add_row().cells
                row[0].text = str(p.get("period")); row[1].text = _fmt(p.get("revenue"), cur)
                row[2].text = _fmt(p.get("net_profit"), cur); row[3].text = str(p.get("net_margin") or "—")
        for fnd in (f.get("key_findings") or [])[:5]:
            d.add_paragraph(fnd, style="List Bullet")

    dd = intel.get("due_diligence")
    if dd:
        d.add_heading("Due Diligence", level=1)
        d.add_paragraph(f"Attractiveness: {dd.get('overall_score')}/100")
        if dd.get("recommendation"): d.add_paragraph(dd["recommendation"])
        if dd.get("red_flags"):
            d.add_paragraph("Red flags:")
            for r in dd["red_flags"][:6]: d.add_paragraph(r, style="List Bullet")

    st = intel.get("strategy")
    if st and st.get("recommendations"):
        d.add_heading("Strategic Recommendations", level=1)
        for r in st["recommendations"][:6]:
            d.add_paragraph(r.get("title", ""), style="List Number")

    d.add_paragraph()
    foot = d.add_paragraph("Generated by AI-BOS · Figures may be AI-extracted; verify before decisions.")
    foot.runs[0].font.size = Pt(8); foot.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    buf = io.BytesIO(); d.save(buf); return buf.getvalue()


# ---------------- 销售 Deck (PPTX) ----------------
def build_sales_deck(intel: dict) -> bytes:
    from pptx import Presentation
    from pptx.util import Inches, Pt

    c = intel["company"]
    prs = Presentation()
    blank, title_layout = prs.slide_layouts[6], prs.slide_layouts[5]

    def bullets_slide(title, lines):
        s = prs.slides.add_slide(title_layout)
        s.shapes.title.text = title
        tb = s.shapes.add_textbox(Inches(0.6), Inches(1.6), Inches(8.8), Inches(5))
        tf = tb.text_frame; tf.word_wrap = True
        for i, ln in enumerate([x for x in lines if x][:8]):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            p.text = f"• {ln}"; p.font.size = Pt(18)

    # 封面（Title Slide 版式，含副标题）
    s0 = prs.slides.add_slide(prs.slide_layouts[0])
    s0.shapes.title.text = c["name"]
    try:
        s0.placeholders[1].text = f"Sales Brief · {c.get('sector') or c.get('industry') or ''} · {date.today().isoformat()}"
    except (KeyError, IndexError):
        pass

    mk = intel.get("market")
    if mk:
        bullets_slide("Market Opportunity", [f"TAM: {mk.get('tam')}", f"SAM: {mk.get('sam')}",
                      f"Growth: {mk.get('market_growth')}"] + (mk.get("trends") or [])[:4])
    comp = intel.get("competitive")
    if comp:
        lines = [comp.get("market_position", "")] + [f"vs {x.get('name')}" for x in (comp.get("competitors") or [])[:5]]
        bullets_slide("Competitive Positioning", lines)
    sa = intel.get("sales")
    if sa:
        bullets_slide("Ideal Customers & Pain Points",
                      [f"ICP: {x.get('segment')}" for x in (sa.get("icp") or [])[:3]] + (sa.get("pain_points") or [])[:4])
    if comp and comp.get("swot", {}).get("strengths"):
        bullets_slide("Why Us", comp["swot"]["strengths"][:6])
    if sa and sa.get("sales_opportunities"):
        bullets_slide("Next Steps", sa["sales_opportunities"][:6])

    buf = io.BytesIO(); prs.save(buf); return buf.getvalue()


# ---------------- Battlecard (DOCX) ----------------
def build_battlecard(intel: dict) -> bytes:
    import docx
    c = intel["company"]
    comp = intel.get("competitive") or {}
    d = docx.Document()
    d.add_heading(f"{c['name']} — Competitive Battlecard", level=0)
    if comp.get("market_position"):
        d.add_paragraph(comp["market_position"])
    sw = comp.get("swot", {})
    if sw.get("strengths"):
        d.add_heading("Our Strengths", level=2)
        for x in sw["strengths"][:6]: d.add_paragraph(x, style="List Bullet")
    if sw.get("weaknesses"):
        d.add_heading("Watch-outs", level=2)
        for x in sw["weaknesses"][:6]: d.add_paragraph(x, style="List Bullet")
    for bc in (comp.get("battlecards") or []):
        d.add_heading(f"vs {bc.get('competitor')}", level=2)
        if bc.get("why_we_win"):
            d.add_paragraph("Why we win:")
            for x in bc["why_we_win"]: d.add_paragraph(x, style="List Bullet")
        if bc.get("why_we_lose"):
            d.add_paragraph("Why we lose:")
            for x in bc["why_we_lose"]: d.add_paragraph(x, style="List Bullet")
        if bc.get("objection_handling"):
            d.add_paragraph("Objection handling:")
            for x in bc["objection_handling"]: d.add_paragraph(x, style="List Bullet")
    buf = io.BytesIO(); d.save(buf); return buf.getvalue()


# ---------------- 外联邮件 (TXT) ----------------
def build_outreach_email(intel: dict) -> str:
    c = intel["company"]
    sa = intel.get("sales") or {}
    pains = (sa.get("pain_points") or [])[:3]
    name = c["name"]
    lines = [f"Subject: Helping {name} tackle {pains[0] if pains else 'key priorities'}", ""]
    lines.append(f"Hi [First Name],")
    lines.append("")
    lines.append(f"I’ve been following {name}'s work in {c.get('industry') or 'your space'} and noticed a few areas where we may be able to help:")
    for p in pains:
        lines.append(f"  • {p}")
    if sa.get("sales_opportunities"):
        lines.append("")
        lines.append("Specifically, we could support:")
        for o in sa["sales_opportunities"][:2]:
            lines.append(f"  • {o}")
    lines += ["", "Would you be open to a 20-minute call next week to explore this?", "",
              "Best regards,", "[Your Name]", "", "— Generated by AI-BOS"]
    return "\n".join(lines)
